@startuml tinyhttp
package team.aurorahub.learn.tinyhttp{

    package team.aurorahub.learn.tinyhttp.Config{
        class TinyLocation {
            -settings : JSONObject
            +TinyLocation()
            +load(refMap : JSONObject) : void
            +check() : boolean
            +getPath() : String
            +setPath(path : String) : void
            +isAccessiable() : Boolean
            +setAccessible(accessiable : boolean) : void
            +getHandlerType() : int
            +setHandlerType(type : int) : void
            +getHandlerPath() : String
            +setHandlerPath(handlerPath : String) : void
        }

        class Config{
            -configFilePath : String
            -customed : boolean
            -domain : String
            -port : int
            -root : String
            -redirect : boolean
            -redirectHost : String
            -redirectPort : String
            -paths : LinkedList<String>
            -locations : HashMap<String, TinyLocation>
            +Config()
            +Config(confPath : String)
            +getConfigFilePath() : String
            +getDomain() : String
            +setDomain(newDomain : String) : void
            +getPort() : int
            +setPort(newPort : int) : void
            +getPaths() : LinkedList<String>
            +getLocation(path : String) : TinyLocation
            +addLocation(newLocation : TinyLocation, newPath : String) : void
            +getRoot() : String
            +setRoot(newRoot : String) : void
            +isRedirect() : boolean
            +setRedirect(newRedirct : boolean) : void
        }

        Config *-left-> TinyLocation
    }

    package team.aurorahub.learn.tinyhttp.model{
        class TinyHttpMsg{
            #contentLen : int
            #headerFields : HashMap<String, String>
            #tinyBody : ByteArrayOutputStream
            #inSocket : InputStream
            +TinyHttpMsg(newInput : InputStream)
            #{abstract}rebuildHeader() : String
            +{abstract}readAllBytesNow() : int
            +getContentLength() : int
            +getParam(key : String) : String
            +setParam(key : String, value : String) : String
            +sendTo(out : OutputStream) : int
            +transferTo(out : OutputStream) : int
            +getInputStream() : InputStream
        }

        class Request{
            #tinyUri : String
            #tinyMethod : String
            #httpVer : String
            #queryParams : HashMap<String, String>
            #tinyQuery : String
            +Request(newIn : InputStream)
            +getUri() : String
            +getHttpMethod() : String
            +getHttpVer() : String
        }

        TinyHttpMsg <|-left- Request

        class Response{
            #httpVer : String
            #statusCode : int
            #codeParse : String
            #fromOuter : boolean
            +Response(newInput : InputStream)
            +Response(code : int)
            +writeBytes0(src : byte[], len : int) : int
            +print(msg : String) : Response
            +println(msg : String) : Response
            +loadFile(path : String) : Response
        }

        TinyHttpMsg <|-- Response
    }
    package team.aurorahub.learn.tinyhttp.Handler{

        class Handler{
            -setting : Config
            -client : Socket
            +Handler(myset : Config, newSocket : Socket)
            -getLocation(uri : String) : String
            +run() : void
        }

        Handler o-left-> Config
        Handler .right.> Request
        Handler ...> Response
    }

    package team.aurorahub.learn.tinyhttp.core{
        class ThreadPoolManager{
            -maxCon : int
            -sSocket : ServerSocket
            -fixThreadPool ：ExecutorService
            +ThreadPoolManager(max : int)
            +run(myConf : Config) : void
        }
        ThreadPoolManager ...> Config
        ThreadPoolManager ...> Handler

        class Server{
            -manager : ThreadPoolManager
            -myConf : Config
            +Server(myConf : Config) : void
            +run() : void
            +{static}main(args : String[]) : void
        }
        Server *-right-> ThreadPoolManager
        Server o--> Config
    }

    package team.aurorahub.learn.tinyhttp.tinyUtils{
        class IoTools{
            +{static}CRLF : String
            +{static}BLANK : String
            +{static}readToString(confPath : String) : String
            +{static}tinyURLDecoding(url : String, encoding : String) : String
            +{static}tinyURLEncoding(url : String, encoding : String) : String
            +{static}tinyStrEncoding(msg String, encoding : String) : byte[]
            +{static}getContentType(target : File) : String
            +{static}formatURI(originURI : String) : String
            +{static}getURLParams(queryStr : String, KVs : HashMap<String, String>) : int
            +{static}getURIQuery(KVs : HashMap<String, String>) : String
        }

        class TinyLogger{
            -{static}logFile : String
            -{static}myLogger : Logger
            -{static}formatter : DateTimeFormatter
            -TinyLogger()
            +{static}setLogPath(path : String) : void
            +{static}getTinyLogger() : Logger
        }

        Handler .down.> TinyLogger
        Server .down.> TinyLogger
        ThreadPoolManager ...>TinyLogger

        class TinyLogFormat{
            -format(record : LogRecord) : String
        }

        TinyLogger+--TinyLogFormat
    }
    TinyLocation .down.> IoTools
    Config .down.> IoTools
    Response .up.> IoTools
    Request .up.> IoTools
}
@enduml